<?php

defined('C5_EXECUTE') or die('Access Denied.');

class RemoPageListAttributeAttributeTypeController extends AttributeTypeController {

	const TABLE_SETTINGS = 'atRemoPagelistAttributeSettings';
	const TABLE_VALUES = 'akRemoPagelistAttributeSelectedPages';

	public function getDisplayValue() {
		return 'display';
	}

	public function getValue() {
		$db = Loader::db();
		$selectedPages = $db->GetCol('SELECT cID FROM ' . self::TABLE_VALUES . ' WHERE avID=?', array($this->getAttributeValueID()));
		return $selectedPages;
	}

	/**
	 * Load attribute type configuration
	 * @return boolean
	 */
	protected function load() {
		$ak = $this->getAttributeKey();
		if (!is_object($ak)) {
			return false;
		}

		$db = Loader::db();
		$row = $db->GetRow('SELECT * FROM ' . self::TABLE_SETTINGS . ' WHERE akID = ?', $ak->getAttributeKeyID());

		unset($row['akID']);

		foreach ($row as $variableName => $variableValue) {
			$this->set('ak' . ucfirst($variableName), $variableValue);
		}

		return true;
	}

	/**
	 * Display type form shown when editing the attribute
	 */
	public function type_form() {
		$collectionTypes = CollectionType::getList();

		$this->load();

		$this->set('collectionTypes', $collectionTypes);
		$this->set('form', Loader::helper('form'));
	}

	public function deleteKey() {
		$db = Loader::db();
	}

	/**
	 * Save type form data
	 * @param Array $data
	 */
	public function saveKey($data) {
		$ak = $this->getAttributeKey();

		$db = Loader::db();

		$selectedPageTypes = '';
		if (array_key_exists('selectedPageTypes', $data)) {
			$selectedPageTypes = join(',', $data['selectedPageTypes']);
		}

		// now we have a collection attribute key object above.
		$db->Replace(self::TABLE_SETTINGS, array(
		    'akID' => $ak->getAttributeKeyID(),
		    'selectedPageTypes' => $selectedPageTypes), array('akID'), true);
	}

	/**
	 * Display form where attribute values can be selected
	 */
	public function form() {
		$this->load();

		// get selected pages
		$db = Loader::db();
		$selectedPages = $this->getValue();
		$this->set('selectedPages', $selectedPages);
	}

	/**
	 * Save form data shown by the form() method
	 * @param Array $data
	 */
	public function saveForm($data) {
		$db = Loader::db();

		$db->Execute('DELETE FROM ' . self::TABLE_VALUES . ' WHERE avID=?', array($this->getAttributeValueID()));

		if (array_key_exists('pageID', $data) && is_array($data['pageID'])) {
			foreach ($data['pageID'] as $cID) {
				$db->Execute('INSERT INTO ' . self::TABLE_VALUES . ' (avID, cID) VALUES (?,?)', array($this->getAttributeValueID(), $cID));
			}
		}
	}

	/**
	 * Display from where the user can select the values to find existing
	 * attribute category entries.
	 */
	public function search() {
		$this->load();
	}

	/**
	 * Searches for the values selected in the form generated by search()
	 * @param DatabaseItemList $list
	 * @return DatabaseItemList
	 */
	public function searchForm($list) {
		$selectedPageIDs = $this->request('atPageID');
		$db = Loader::db();

		if (is_array($selectedPageIDs)) {
			$list->filter(false, '(p1.cID IN (' . join(',', $selectedPageIDs) . '))');
		}
		return $list;
	}

}
